### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/infinite-theme#29]
Hi,
what version of Bootstrap-sass is used here?

Just variables.scss looking different (for example num of columns: https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L330)

Is it without changes in lib or not?
What about using via bower?

Thanks

**Comment by landsman** [comment]
OK, I can fix this deprecated using in my fork.
Tell me please, what is the most "up-date" branch for this changes?

**Comment by dbosen** [comment]
@goldquest can you help out here?

**Comment by landsman** [comment]
I am using Infinite as parent theme and bootstrap in theme is deprecated. I can refactor it and switch bootstrap as bower component. I see that branche https://github.com/BurdaMagazinOrg/infinite-theme/tree/8.x-2.x is most alive - should I do this change here?

**Comment by tjwelde** [comment]
The branch 8.x-1.x is maintained by the thunder team, but we provide only support, not new features.
The branch 8.x-2.x is actively developed by a Burda publisher.

**Comment by landsman** [comment]
I don't know what is difference between Thunder team and Burda publisher.
What plans to with 8.x-1.x ?

**Comment by tjwelde** [comment]
We just plan to keep it stable and functional

**Comment by landsman** [comment]
OK, so new things should be in 8.x-2.x, right?

**Comment by tjwelde** [comment]
The 8.x-2.x branch is not guaranteed to be installable, so it is not really meant for the public. But you can try. It has some different features and concepts.
If you think, it would be valuable for other users to have a newer bootstrap version, you can make a Pull Request to 8.x-1.x.

**Comment by landsman** [comment]
Ok. 
Why Burdas branch will not be merged by PR in future if is newest?

**Comment by tjwelde** [comment]
The Infinite Theme 8.x-2.x is a branch which the publisher Burdastyle is using internally for their own projects. It is not build for public use, since it needs a strict environment.
The 8.x-1.x branch is a public branch, which will get changes from 8.x-2.x when useful.

**Comment by landsman** [comment]
Yeah I already understand.
I mean that we have two separate worlds without communication between themselves(?). PR with basic fix / changes for others can be useful.
Its a pity!

**Comment by dbosen** [comment]
It is not so much a problem of communication, it is more that we are right not able to provide the integration of infinite 2 to thunder. It is really more a problem of ressources.

**Comment by tjwelde** [comment]
As I said, changes will be cherry-picked if they are useful, compatible and stable.
If you want to introduce a new bootstrap version to 8.x-1.x feel free to open a PR. Bower would be fine for that, since we are already using it for other things in the thunder distribution.

**Comment by landsman** [comment]
OK, thanks for informations guys. I'll create PR.

**Comment by landsman** [comment]
I have prepared refactored theme to up-date bootstrap with gulp.
How can I register a startup tasks during installation (bower install, gulp sass) ?

**Comment by tjwelde** [comment]
For composer based installs you can add a composer script to the `composer.json`. See e.g. https://github.com/BurdaMagazinOrg/thunder-project/blob/8.x/composer.json#L50

Since the theme should always be shippable as is, I would say you should still include a transpiled css file. You could then add commands to `composer.json` also as seen in the example.

**Comment by landsman** [comment]
Transpiled css in git repository? Ughs :(
