### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/infinite-theme#30]
Hi, I am using Infinite as parent theme. How can I override library infinite.external with “zero” content? I don’t want Pinterest lib loading.

**Comment by tjwelde** [comment]
Please have a look at the Drupal Documentation. I found the document you've been searching for here: https://www.drupal.org/docs/8/theming-drupal-8/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-theme.
Have a look under "Overriding and extending libraries".

**Comment by landsman** [comment]
I am using overriding libraries but how can I say: "override infinite.external to null" ? 
It makes errors.

**Comment by tjwelde** [comment]
I tried it with defining
```
libraries-override:
  infinite/infinite.external: false
```
in `infinite_child.info.yml` and it works without errors on my side.
Can you post a screenshot of the error?
