### ISSUE TITLE
Detect language code from system

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/infinite-theme#31]
Please can you add this feature? :-)

- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/templates/embeds/api_fb.html.twig#L19

- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/infinite.theme#L58
 
- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/templates/system/html.html.twig#L27

As new feature should be FB pixel support:

```<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init', '{{ fb_pixel_id }}');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id={{ fb_pixel_id }}&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
```

**Comment by tjwelde** [comment]
Are those two things related?

**Comment by landsman** [comment]
Nope but you can add this javascript to "api_fb.html.twig" for future.

**Comment by tjwelde** [comment]
Yes, I will include the file depending on the drupal language

**Comment by landsman** [comment]
Thank you

**Comment by tjwelde** [comment]
could you please move the FB pixel support to a separate issue?

**Comment by landsman** [comment]
yop

**Comment by landsman** [comment]
Next thing about language detection in theme is "jquery.timeago".

Library have language packs: https://github.com/rmm5t/jquery-timeago/tree/master/locales but how load just one, what we need? :-) theme.libs is not good for it. It good for one file including.

What about some universal language detection support in Thunder for modules, themes to future? Improve Drupal languages - iso code, flag, etc. Add some global functions for work with actual language etc.

These things should by dynamic.

**Comment by tjwelde** [comment]
We can not provide multi-language support atm. But we would be very happy, if someone could investigate it ;)

**Comment by landsman** [comment]
ok
