### ISSUE TITLE
Compass dependency

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/infinite-theme#33]
Hi,
is possible do sass compilation without compass? 

He is crazy :) His process is: 
1. delete compiled css,
2. try compile sass => if he found error, die => result is site without CSS. 

I think that environment without Ruby should be lighter. We have NodeJS and can use it. For example Gulp with: https://www.npmjs.com/package/gulp-sass

I can do this with #29, hm?

**Comment by landsman** [comment]
For example today I got a build error about compass:

`[31m error [0m sass/pages/_page-front.scss (Line 9: Undefined variable: "$screen-md-min".)`

Variable exist, sass import of bootstrap is fine. For second try It was works. Its crazy...

**Comment by tjwelde** [comment]
hmm, wierd.
We are dependent on compass, since the theme is using some functionalities of it (AFAIK).
If you can find out, if compass is not necessary at all, or can be replaced by custom functions, we can talk about removing it.

**Comment by tjwelde** [comment]
on my machine the compiled css file is not deleted. I included an error, but the file was still there. Do you use `compass compile` without providing any more arguments?

**Comment by landsman** [comment]
Yes, `compass compile` or `compass watch` ... just it.

**Comment by tjwelde** [comment]
ah, I see. The css file only contains the errors

**Comment by tjwelde** [comment]
But I think this is expected behaviour and when you have an error in your sass file, you should fix it first. You can always go back to a functioning css version via git...

**Comment by landsman** [comment]
Sure.
Compass is weird. 
Compilation via npm based plugin will be better.
I am good with gulp, its quick and show build time.

**Comment by tjwelde** [comment]
We will keep compass for now, since it is the standard framework for sass and we don't have the resources, to replace everything.
In your child theme you can use a gulp workflow nevertheless

**Comment by landsman** [comment]
I can replace it with refactoring bootstrap to bower.
Gulp need ruby, compass too because "core" sass files have dependecies to it, unnecessarily.

**Comment by tjwelde** [comment]
We digged a liitle bit into it. It is mainly the mixins: `translateY` and `inline-block` and the css reset. Unfortunately, the translateY depends the compass prefix function: `prefix-usage`, which is used to determine a threshold, to decide, if it should be prefixed, or not. Maybe it could be refactored, but you would have to dig into it.

**Comment by tjwelde** [comment]
can we have different pull requests for each functionality, you are adding? E.g. one for bower, one for removal of compass, one for including it in the gulp workflow?

**Comment by landsman** [comment]
Thank you for your reply. Yes these steps are possible. I'll remember on it.

**Comment by landsman** [comment]
We can close this issue :)
