### ISSUE TITLE
Blazy not firing

### ISSUE THREAD

**Issue by drmedrme** [BurdaMagazinOrg/infinite-theme#55]
Setup Windows 10
Vagrant DrupalVM, Acq Desktop, Ubuntu
Thunder 8.1.4

I have tried out the thunder distribution with infinite theme on various dev setups (simplytest.me, vagrant, acquia desktop).  On each demo that I run, the blazy images don't seem to fire when the infinite scroll starts.  So if I click on an article that has images, the first few articles will have the blazy images appearing, but as I scroll down the page and new articles are loaded, the blazy images are not loading and the spinner keeps spinning.   When I run Chrome Dev toosl, I can see the src http file is in the styles directory and it exists.  The styles directory has the correct permissions (775 or 777 to test).  Also if opened that article that has the non-firing blazy image in a new tab, the image appears, but the infinite loading articles that follow will also have non-firing blazy images.

I have also checked libraries to make sure they exists.  I looked at this [Blazy Help](https://github.com/dinbror/blazy/issues/24) to see if it would help, but no luck either.

Any thoughts would be appreciated.

**Comment by landsman** [comment]
I don't need Blazy,
you can do it pure without it.

Look on: http://www.instyle.de

**Comment by drmedrme** [comment]
Thanks.  Will have a look at that.  I noted blazy in the div classes on instyle.de so I thought they were using it.  But will check.

**Comment by drmedrme** [comment]
As a follow up.  I changed the format of the image from Blazy to Image in the Structure/Media Bundles/Image/Manage Display.  It doesn't quite have the smoothness of a blazy load, but it works well.
Thanks for help.
